@startuml Standart Bank System Context Diagram
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title System Context Diagram for credit application processing

Person(user, "Пользователь", "Взаимодействует с системой банка через мобильное приложение и веб-приложение, подает заявку на кредит")

System(system, "Банковая система")

System_Ext(smsGateway, "СМС провайдер")
System_Ext(creditSystem, "Кредитный конвейер")
System_Ext(scoringSystem, "Система оценки клиентов")

Rel(user, system, "Подача новой заявки через веб-сайт/интернет-банк")

Rel(system, creditSystem, "Передача заявки в кредитный конвейер")
Rel(creditSystem, scoringSystem, "Запрос рейтинга клиента у системы оценки")
Rel(system, smsGateway, "Отправка SMS уведомлений (принятие/отклонение/уточнение)")

@enduml